### ISSUE TITLE
not working...failed error

### ISSUE THREAD

**Issue by EdithX** [RohanDebroy/Bypass-Ad-Shorteners#1]
***** Started Bypassing *****

{'status': 'failed'} 

***** Bypass completed *****

***** Started Bypassing Recursively *****

{'status': 'failed'} 

***** Recursive Bypass completed *****

**Comment by EdithX** [comment]
https://github.com/FastForwardTeam/FastForward

can you make for this  if possible

**Comment by RohanDebroy** [comment]
> ***** Started Bypassing *****
> 
> {'status': 'failed'}
> 
> ***** Bypass completed *****
> 
> ***** Started Bypassing Recursively *****
> 
> {'status': 'failed'}
> 
> ***** Recursive Bypass completed *****

Hey,
FYI this is just a wrapper for [this ](https://chrome.google.com/webstore/detail/auto-link-bypasser/doiagnjlaingkmdjlbfalakpnphfmnoh) extension by [Yuumari](https://yuumari.com/). Also, the list of supported domains changes from time to time. So what I would suggest is to check [here ](https://yuumari.com/ex/alb/#domains) whether your URL domain is supported or not.

And on my end, I will see whether Yuumari made any new changes to the extension, which has to be fixed in this repo for my python wrapper to work.


> https://github.com/FastForwardTeam/FastForward
> 
> can you make for this if possible

Yup this can be done. But it might take some time because I am working on something different right now.

**Comment by EdithX** [comment]
Okay bruh

Thank you 

Pls do this 
https://github.com/FastForwardTeam/FastForward
When you are free because it can bypass almost all shorteners
